import {FlashcardsData} from "../type/flash-card.type";

const baseUrl = 'https://home-page-api-34607.herokuapp.com/flash-cards';

export async function getFlashCards(): Promise<FlashcardsData> {
  try {
    const response = await fetch(baseUrl, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json'
      },
      cache: 'no-store',
    });

    return (await response.json()) as FlashcardsData;
  } catch (error) {
    console.log(error);
    return getLocalCards(error);
  }
}

function getLocalCards(error: any): Promise<FlashcardsData> {
  return Promise.resolve({
    categories: [
      {
        id: '1',
        name: 'Medical Coding',
        subCategories: [
          {
            id: '1-1',
            name: '100 Words',
            flashCards:
              [
                {id: "1", question: "gastr-", answer: "Stomach", example: ""},
                {id: "2", question: "cardi-", answer: "Heart", example: ""},
                {id: "3", question: "megal-", answer: "Enlarged", example: ""},
                {id: "4", question: "-itis", answer: "Inflammation", example: ""},
                {id: "5", question: "dermat-", answer: "Skin", example: ""},
                {id: "6", question: "plast-", answer: "Surgical repair", example: ""},
                {id: "7", question: "cerebr-", answer: "Brain", example: ""},
                {id: "8", question: "path-", answer: "Disease", example: ""},
                {id: "9", question: "-ectomy", answer: "Surgical removal", example: ""},
                {id: "10", question: "enter-", answer: "Intestines", example: ""},
                {id: "11", question: "-osis", answer: "Any condition", example: ""},
                {id: "12", question: "-otomy", answer: "Cut into", example: ""},
                {id: "13", question: "aden-", answer: "gland", example: ""},
                {id: "14", question: "angi-", answer: "Vessel", example: ""},
                {id: "15", question: "-oma", answer: "Tumor", example: ""},
                {id: "16", question: "nephr-", answer: "Kidney", example: ""},
                {id: "17", question: "hepat-", answer: "Liver", example: ""},
                {id: "18", question: "arthr-", answer: "Joint", example: ""},
                {id: "19", question: "blephar-", answer: "eyelid", example: ""},
                {id: "20", question: "-ologist", answer: "Specialist", example: ""},
                {id: "21", question: "rhin-", answer: "Nose", example: ""},
                {id: "22", question: "gingiv-", answer: "gum", example: ""},
                {id: "23", question: "-malacia", answer: "Soft", example: ""},
                {id: "24", question: "-ology", answer: "The study of", example: ""},
                {id: "25", question: "Spasm", answer: "Involuntary contractions", example: ""},
                {id: "26", question: "-algia", answer: "pain", example: ""},
                {id: "27", question: "crani-", answer: "skull", example: ""},
                {id: "28", question: "end-", answer: "Inside, within", example: ""},
                {id: "29", question: "hemi-", answer: "half", example: ""},
                {id: "30", question: "-oid", answer: "like", example: ""},
                {id: "31", question: "hyper-", answer: "Above, more than normal", example: ""},
                {id: "32", question: "cyst-", answer: "Sac containing fluid", example: ""},
                {id: "33", question: "chole-", answer: "bile", example: ""},
                {id: "34", question: "hypo-", answer: "under", example: ""},
                {id: "35", question: "-scop-", answer: "observe", example: ""},
                {id: "36", question: "hyster-", answer: "uterus", example: ""},
                {id: "37", question: "-ostomy", answer: "Create an opening", example: ""},
                {id: "38", question: "para-", answer: "Beside, beyond", example: ""},
                {id: "39", question: "-lysis", answer: "Loosening, destruction", example: ""},
                {id: "40", question: "cervic-", answer: "neck", example: ""},
                {id: "41", question: "chondr-", answer: "cartilage", example: ""},
                {id: "42", question: "cyan-", answer: "blue", example: ""},
                {id: "43", question: "hem(at)-", answer: "blood", example: ""},
                {id: "44", question: "ost-", answer: "bone", example: ""},
                {id: "45", question: "psycho-", answer: "mind", example: ""},
                {id: "46", question: "lip-", answer: "fat", example: ""},
                {id: "47", question: "my-", answer: "muscle", example: ""},
                {id: "48", question: "lith-", answer: "stone", example: ""},
                {id: "49", question: "opthalm- opt-", answer: "Eye", example: ""},
                {id: "50", question: "proct-", answer: "Anus", example: ""},
                {id: "51", question: "cost-", answer: "Rib", example: ""},
                {id: "52", question: "-gram", answer: "Record", example: ""},
                {id: "53", question: "acro-", answer: "Extremities", example: ""},
                {id: "54", question: "rhexis", answer: "Break, burst", example: ""},
                {id: "55", question: "carcin-", answer: "Cancer", example: ""},
                {id: "56", question: "-penia", answer: "Decrease", example: ""},
                {id: "57", question: "gen-", answer: "Original, production", example: ""},
                {id: "58", question: "burso-", answer: "Sac", example: ""},
                {id: "59", question: "retr(o)-", answer: "Backwards", example: ""},
                {id: "60", question: "trip-", answer: "Rub, friction", example: ""},
                {id: "61", question: "strept-", answer: "Twist", example: ""},
                {id: "62", question: "-desis", answer: "Binding", example: ""},
                {id: "63", question: "mani-", answer: "Madness", example: ""},
                {id: "64", question: "glosso-", answer: "Tongue", example: ""},
                {id: "65", question: "-trophy", answer: "Development", example: ""},
                {id: "66", question: "supra-", answer: "Above", example: ""},
                {id: "67", question: "-ptosis", answer: "Falling", example: ""},
                {id: "68", question: "-dyn-", answer: "Pain", example: ""},
                {id: "69", question: "mast-", answer: "Breast", example: ""},
                {id: "70", question: "-rrhaphy", answer: "Suture", example: ""},
                {id: "71", question: "dent-", answer: "Teeth", example: ""},
                {id: "72", question: "cephal-", answer: "Head", example: ""},
                {id: "73", question: "auto-", answer: "Self", example: ""},
                {id: "74", question: "epi-", answer: "Upon", example: ""},
                {id: "75", question: "hydro-", answer: "Water", example: ""},
                {id: "76", question: "lobo-", answer: "Section", example: ""},
                {id: "77", question: "-emesis", answer: "Vomiting", example: ""},
                {id: "78", question: "contra-", answer: "Against, counter", example: ""},
                {id: "79", question: "-iasis", answer: "Condition", example: ""},
                {id: "80", question: "trans-", answer: "Through, across", example: ""},
                {id: "81", question: "brady-", answer: "Slow", example: ""},
                {id: "82", question: "-ectasis", answer: "Expansion", example: ""},
                {id: "83", question: "cyt-", answer: "Cell", example: ""},
                {id: "84", question: "odont-", answer: "Tooth", example: ""},
                {id: "85", question: "leuk-", answer: "White", example: ""},
                {id: "86", question: "-esthesia", answer: "Sensation", example: ""},
                {id: "87", question: "cantho-", answer: "Angle at the end of the eyelid", example: ""},
                {id: "88", question: "steno-", answer: "Narrow, contracted", example: ""},
                {id: "89", question: "cheil-", answer: "Lip", example: ""},
                {id: "90", question: "-cele", answer: "hernia", example: ""},
                {id: "91", question: "benign", answer: "Mild, not cancerous", example: ""},
                {id: "92", question: "semen", answer: "Seed", example: ""},
                {id: "93", question: "celio-", answer: "Abdomen", example: ""},
                {id: "94", question: "erythro-", answer: "Red", example: ""},
                {id: "95", question: "vaso-", answer: "Vessel", example: ""},
                {id: "96", question: "melan-", answer: "Black", example: ""},
                {id: "97", question: "cauda-", answer: "Tail", example: ""},
                {id: "98", question: "lingua-", answer: "Tongue", example: ""},
                {id: "99", question: "myring-", answer: "Eardrum", example: ""},
                {id: "100", question: "spondyl-", answer: "Spinal column", example: ""},
              ],
          },
          {
            id: '1-2',
            name: '50 Abbreviations',
            flashCards: [
              {id: "1", question: "WBC", answer: "White Blood Cells", example: "WBC is low"},
              {id: "2", question: "ENT", answer: "Ears Nose & Throat", example: ""},
              {id: "3", question: "AMA", answer: "American Medical Association", example: ""},
              {id: "4", question: "BP", answer: "Blood Pressure", example: ""},
              {id: "5", question: "dx", answer: "Diagnosis", example: ""},
              {id: "6", question: "RBC", answer: "Red Blood Cell", example: ""},
              {id: "7", question: "SOB", answer: "Shortness of Breath", example: ""},
              {id: "8", question: "WHO", answer: "World Health Organization", example: ""},
              {id: "9", question: "WNL", answer: "Within Normal Limits", example: ""},
              {id: "10", question: "OD", answer: "Overdose", example: ""},
              {id: "11", question: "CBC", answer: "Complete Blood Count", example: ""},
              {id: "12", question: "sx", answer: "Symptoms", example: ""},
              {id: "13", question: "bx", answer: "Biopsy", example: ""},
              {id: "14", question: "DM", answer: "Diabetes Mellitus", example: ""},
              {id: "15", question: "AKI", answer: "Acute Kidney Injury", example: ""},
              {id: "16", question: "CAD", answer: "Coronary Artery Disease", example: ""},
              {id: "17", question: "ASD", answer: "Atrial Septal Defect", example: ""},
              {id: "18", question: "COPD", answer: "Chronic Obstructive Pulmonary Disease", example: ""},
              {id: "19", question: "CVA", answer: "Cerebrovascular Accident", example: ""},
              {id: "20", question: "MI", answer: "Myocardial Infarction", example: ""},
              {id: "21", question: "OSA", answer: "Obstructive Sleep Apnea", example: ""},
              {id: "22", question: "TSH", answer: "Thyroid Stimulating Hormone", example: ""},
              {id: "23", question: "H&P", answer: "History & Physical", example: ""},
              {id: "24", question: "ROS", answer: "Review of Symptoms", example: ""},
              {id: "25", question: "ED", answer: "Emergency Department", example: ""},
              {id: "26", question: "ICU", answer: "Intensive Care Unit", example: ""},
              {id: "27", question: "CPT", answer: "Current Procedural Terminology", example: ""},
              {id: "28", question: "ICD", answer: "International Classification of Disease", example: ""},
              {id: "29", question: "OTC", answer: "Over the Counter", example: ""},
              {id: "30", question: "DJD", answer: "Degenerative Joint Disease", example: ""},
              {id: "31", question: "NSAID", answer: "Non-Steroidal Anti-Inflammatory Drugs", example: ""},
              {id: "32", question: "CHF", answer: "Congestive Heart Failure", example: ""},
              {id: "33", question: "TB", answer: "Tuberculosis", example: ""},
              {id: "34", question: "IUD", answer: "Intrauterine Device", example: ""},
              {id: "35", question: "LMP", answer: "Last Menstrual Period", example: ""},
              {id: "36", question: "TBSA", answer: "Total Body Surface Area", example: ""},
              {id: "37", question: "DVT", answer: "Deep Vein Thrombosis", example: ""},
              {id: "38", question: "PE", answer: "Pulmonary Embolism", example: ""},
              {id: "39", question: "TIA", answer: "Transient Ischemic Attack", example: ""},
              {id: "40", question: "CABG", answer: "Coronary Artery Bypass Graft", example: ""},
              {id: "41", question: "DDD", answer: "Degenerative Disc Disease", example: ""},
              {id: "42", question: "fx", answer: "Fracture", example: ""},
              {id: "43", question: "HTN", answer: "Hypertension", example: ""},
              {id: "44", question: "I&D", answer: "Incision and Drainage", example: ""},
              {id: "45", question: "IBS", answer: "Irritable Bowel Syndrome", example: ""},
              {id: "46", question: "IM", answer: "Intramuscular", example: ""},
              {id: "47", question: "PUD", answer: "Peptic Ulcer Disease", example: ""},
              {id: "48", question: "RA", answer: "Rheumatoid Arthritis", example: ""},
              {id: "49", question: "SQ", answer: "Subcutaneous", example: ""},
              {id: "50", question: "UTI", answer: "Urinary Tract Infection", example: ""},
            ]
          }
        ]
      },
      {
        id: '2',
        name: `${error}`,
        subCategories: []
      }
    ]
  });
}
